version: '3.8'
services:
    go-api:
        build: .
        tty: true
        volumes:
            - .:/go/src/go-api
        ports:
            - "8080:8080"
    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: go-api
            POSTGRES_PASSWORD: go-api
            POSTGRES_DB: go-api
        ports:
            - 5432:5432